apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $PROJECT_NAME
  name: devops-go-sample
  labels:
    app: devops-go-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-go-sample
  template:
    metadata:
      labels:
        app: devops-go-sample
    spec:
      containers:
      - name: go
        image: $REGISTRY/$DOCKERHUB_USERNAME/$APP_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: go-sample-service
  namespace: $PROJECT_NAME
spec:
  selector:
    app: devops-go-sample
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
